### Cross Validation (k-fold)

#### KNN classifier with fruit Dataset(2 features)

In [21]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import cross_val_score
from sklearn.neighbors import KNeighborsClassifier
fruits_data = pd.read_table("../DataFiles/fruit_data_with_colors.txt")
X,y = fruits_data[['height', 'width']].as_matrix(),(fruits_data['fruit_label']==1).as_matrix()
knn = KNeighborsClassifier(n_neighbors=5)
cv_scores = cross_val_score(knn,X,y)
print "Cross-validation scores(3-fold): {}".format(cv_scores)
print "Mean cross-validation score(3-fold): {:.3f}".format(np.mean(cv_scores))

Cross-validation scores(3-fold): [ 0.66666667  0.47368421  0.89473684]
Mean cross-validation score(3-fold): 0.678


#### Validation curve

In [20]:
from sklearn.svm import SVC
from sklearn.model_selection import validation_curve
param_range = np.logspace(-3,3,4)
svm_clf = SVC()
train_scores, test_scores = validation_curve(svm_clf,X,y,param_name="gamma",param_range=param_range,cv=3)
print train_scores
print test_scores
plt.figure()
plt.plot()

[[ 0.68421053  0.675       0.675     ]
 [ 0.89473684  0.875       0.675     ]
 [ 0.86842105  0.975       0.875     ]
 [ 1.          1.          0.975     ]]
[[ 0.66666667  0.68421053  0.68421053]
 [ 0.42857143  0.47368421  0.68421053]
 [ 0.71428571  0.63157895  0.89473684]
 [ 0.71428571  0.63157895  0.73684211]]
